function GetMagicLorePoolDataResources()
    return {
        -- Battle Lores
        Beasts = {
            InnateSkill = {"wh_dlc03_skill_magic_beasts_wild_heart",},
            SignatureSpell = {"wh_dlc03_skill_magic_beasts_dummy_wyssans_wildform", },
            Level1DefaultSpells = {"wh_dlc03_skill_magic_beasts_flock_of_doom", "wh_dlc03_skill_magic_beasts_panns_impenetrable_pelt", "wh_dlc03_skill_magic_beasts_the_amber_spear", },
            Level1DefaultSpellsLord = {"wh2_main_skill_magic_beasts_flock_of_doom_lord", "wh2_main_skill_magic_beasts_panns_impenetrable_pelt_lord", "wh2_main_skill_magic_beasts_the_amber_spear_lord",},
            Level3DefaultSpells = {"wh_dlc03_skill_magic_beasts_the_curse_of_anraheir", "wh_dlc03_skill_magic_beasts_transformation_of_kadon", },    
            Level3DefaultSpellsLord = {"wh2_main_skill_magic_beasts_the_curse_of_anraheir_lord", "wh2_main_skill_magic_beasts_transformation_of_kadon_lord",},
        },
        Death = {
            InnateSkill = {"wh_main_skill_all_magic_death_03_life_leeching",},
            SignatureSpell = {"wh_main_skill_all_magic_death_dummy_spirit_leech", },
            Level1DefaultSpells = {"wh_main_skill_all_magic_death_02_aspect_of_the_dreadknight", "wh_main_skill_all_magic_death_05_doom_and_darkness", "wh_main_skill_all_magic_death_04_soulblight", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_death_02_aspect_of_the_dreadknight_lord", "wh2_main_skill_all_magic_death_05_doom_and_darkness_lord", "wh2_main_skill_all_magic_death_04_soulblight_lord",},
            Level3DefaultSpells = {"wh_main_skill_all_magic_death_09_the_fate_of_bjuna", "wh_main_skill_all_magic_death_10_the_purple_sun_of_xereus", },
            Level3DefaultSpellsLord = { "wh2_main_skill_all_magic_death_09_the_fate_of_bjuna_lord", "wh2_main_skill_all_magic_death_10_the_purple_sun_of_xereus_lord",},
        },
        Fire = {
            InnateSkill = {"wh_main_skill_all_magic_fire_04_kindleflame",},
            SignatureSpell = {"wh_main_skill_all_magic_fire_dummy_fireball",},
            Level1DefaultSpells = {"wh_main_skill_all_magic_fire_02_cascading_fire-cloak", "wh_main_skill_all_magic_fire_03_flaming_sword_of_rhuin", "wh_main_skill_all_magic_fire_05_the_burning_head", },
            Level1DefaultSpellsLord  = {"wh2_main_skill_all_magic_fire_02_cascading_fire-cloak_lord", "wh2_main_skill_all_magic_fire_03_flaming_sword_of_rhuin_lord", "wh2_main_skill_all_magic_fire_05_the_burning_head_lord"},
            Level3DefaultSpells = {"wh_main_skill_all_magic_fire_09_piercing_bolts_of_burning", "wh_main_skill_all_magic_fire_10_flame_storm",},
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_fire_09_piercing_bolts_of_burning_lord" ,"wh2_main_skill_all_magic_fire_10_flame_storm_lord"},
        },
        Heavens = {
            InnateSkill = {"wh_main_skill_all_magic_heavens_03_rolling_skies",},
            SignatureSpell = {"wh_main_skill_all_magic_heavens_dummy_harmonic_convergence",},
            Level1DefaultSpells = {"wh_main_skill_all_magic_heavens_02_wind_blast", "wh_main_skill_all_magic_heavens_04_curse_of_the_midnight_wind", "wh_main_skill_all_magic_heavens_05_urannons_thunderbolt", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_heavens_02_wind_blast_lord", "wh2_main_skill_all_magic_heavens_04_curse_of_the_midnight_wind_lord", "wh2_main_skill_all_magic_heavens_05_urannons_thunderbolt_lord",},
            Level3DefaultSpells = {"wh_main_skill_all_magic_heavens_09_comet_of_casandora", "wh_main_skill_all_magic_heavens_10_chain_lightning", },
            Level3DefaultSpellsLord = { "wh2_main_skill_all_magic_heavens_09_comet_of_casandora_lord", "wh2_main_skill_all_magic_heavens_10_chain_lightning_lord", },
        },
        Life = {
            InnateSkill = {"wh_dlc05_skill_magic_life_life_bloom",},
            SignatureSpell = {"wh_dlc05_skill_magic_life_wizard_awakening_of_the_wood_dummy", },
            Level1DefaultSpells = {"wh_dlc05_skill_magic_life_wizard_earth_blood", "wh_dlc05_skill_magic_life_wizard_shield_of_thorns", "wh_dlc05_skill_magic_life_wizard_flesh_to_stone", },
            Level1DefaultSpellsLord = {"wh2_main_skill_magic_life_wizard_earth_blood_lord", "wh2_main_skill_magic_life_wizard_shield_of_thorns_lord", "wh2_main_skill_magic_life_wizard_flesh_to_stone_lord",},
            Level3DefaultSpells = {"wh_dlc05_skill_magic_life_wizard_regrowth", "wh_dlc05_skill_magic_life_wizard_the_dwellers_below", },
            Level3DefaultSpellsLord = {"wh2_main_skill_magic_life_wizard_regrowth_lord", "wh2_main_skill_magic_life_wizard_the_dwellers_below_lord",},
        },
        Light = {
            InnateSkill = {"wh_main_skill_all_magic_light_03_exorcism",},
            SignatureSpell = {"wh_main_skill_all_magic_light_dummy_shems_burning_gaze",},
            Level1DefaultSpells = {"wh_main_skill_all_magic_light_02_phas_protection", "wh_main_skill_all_magic_light_04_light_of_battle", "wh_main_skill_all_magic_light_05_net_of_amyntok"},
            Level1DefaultSpellsLord = {"wh_main_skill_all_magic_light_02_phas_protection", "wh_main_skill_all_magic_light_04_light_of_battle", "wh_main_skill_all_magic_light_05_net_of_amyntok"},
            Level3DefaultSpells = {"wh_main_skill_all_magic_light_09_banishment", "wh_main_skill_all_magic_light_10_bironas_timewarp", },
            Level3DefaultSpellsLord = {"wh_main_skill_all_magic_light_09_banishment", "wh2_main_skill_all_magic_light_10_bironas_timewarp_lord", },
        },
        Metal = {
            InnateSkill = {"wh_main_skill_all_magic_metal_03_metalshifting",},
            SignatureSpell = {"wh_main_skill_all_magic_metal_dummy_searing_doom",},
            Level1DefaultSpells = {"wh_main_skill_all_magic_metal_02_plague_of_rust", "wh_main_skill_all_magic_metal_04_glittering_robe", "wh_main_skill_all_magic_metal_05_gehennas_golden_hounds", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_metal_02_plague_of_rust_lord", "wh2_main_skill_all_magic_metal_04_glittering_robe_lord", "wh2_main_skill_all_magic_metal_05_gehennas_golden_hounds_lord", },
            Level3DefaultSpells = {"wh_main_skill_all_magic_metal_09_transmutation_of_lead", "wh_main_skill_all_magic_metal_10_final_transmutation", },
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_metal_09_transmutation_of_lead_lord" , "wh2_main_skill_all_magic_metal_10_final_transmutation_lord", },
        },
        Shadows = {
            InnateSkill = {"wh_dlc05_skill_magic_shadow_smoke_and_mirrors", },
            SignatureSpell = {"wh_dlc05_skill_magic_shadow_mystifying_miasma_dummy",},
            Level1DefaultSpells = {"wh_dlc05_skill_magic_shadow_enfeebling_foe",  "wh_dlc05_skill_magic_shadow_the_withering", "wh_dlc05_skill_magic_shadow_penumbral_pendulum", },
            Level1DefaultSpellsLord = {"wh2_main_skill_magic_shadow_enfeebling_foe_lord", "wh2_main_skill_magic_shadow_the_withering_lord", "wh2_main_skill_magic_shadow_penumbral_pendulum_lord", },
            Level3DefaultSpells = {"wh_dlc05_skill_magic_shadow_pit_of_shades", "wh_dlc05_skill_magic_shadow_okkams_mindrazor", },
            Level3DefaultSpellsLord = {"wh2_main_skill_magic_shadow_pit_of_shades_lord", "wh2_main_skill_magic_shadow_okkams_mindrazor_lord", },
        },
        -- Unique lores
        Vampires = {
            InnateSkill = {"wh_main_skill_vmp_magic_vampires_03_the_curse_of_undeath",},
            SignatureSpell = {"wh_main_skill_vmp_magic_vampires_dummy_invocation_of_nehek", },
            Level1DefaultSpells = {"wh_main_skill_vmp_magic_vampires_02_vanhels_danse_macabre", "wh_main_skill_vmp_magic_vampires_04_gaze_of_nagash", "wh_main_skill_vmp_magic_vampires_05_raise_dead"},
            Level1DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_02_vanhels_danse_macabre_lord", "wh2_main_skill_vmp_magic_vampires_04_gaze_of_nagash_lord", "wh2_main_skill_vmp_magic_vampires_05_raise_dead_lord", },
            Level3DefaultSpells = {"wh_main_skill_vmp_magic_vampires_09_curse_of_years", "wh_main_skill_vmp_magic_vampires_10_wind_of_death", },
            Level3DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_09_curse_of_years_lord", "wh2_main_skill_vmp_magic_vampires_10_wind_of_death_lord", },
        },
        VampiresDeeps = {
            InnateSkill = {"wh_main_skill_vmp_magic_vampires_03_the_curse_of_undeath",},
            SignatureSpell = {"wh_main_skill_vmp_magic_vampires_01_invocation_of_nehek", },
            Level1DefaultSpells = {"wh_main_skill_vmp_magic_vampires_02_vanhels_danse_macabre", "wh_main_skill_vmp_magic_vampires_04_gaze_of_nagash", "wh2_dlc11_skill_cst_magic_vampires_05_drowned_dead", },
            Level1DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_02_vanhels_danse_macabre_lord", "wh2_main_skill_vmp_magic_vampires_04_gaze_of_nagash_lord", "wh2_dlc11_skill_cst_magic_vampires_05_drowned_dead_lord", },
            Level3DefaultSpells = {"wh_main_skill_vmp_magic_vampires_09_curse_of_years", "wh_main_skill_vmp_magic_vampires_10_wind_of_death", },
            Level3DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_09_curse_of_years_lord", "wh2_main_skill_vmp_magic_vampires_10_wind_of_death_lord", },
        },
        High = {
            InnateSkill = {"wh2_main_skill_all_magic_high_03_lore_attribute",},
            SignatureSpell = {"wh2_main_skill_all_magic_high_dummy_apotheosis", },
            Level1DefaultSpells = {"wh2_main_skill_all_magic_high_04_hand_of_glory", "wh2_main_skill_all_magic_high_01_soul_quench", "wh2_main_skill_all_magic_high_05_tempest",},
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_high_04_hand_of_glory", "wh2_main_skill_all_magic_high_01_soul_quench", "wh2_main_skill_all_magic_high_05_tempest",},
            Level3DefaultSpells = {"wh2_main_skill_all_magic_high_09_arcane_unforging", "wh2_main_skill_all_magic_high_10_fiery_convocation"},
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_high_09_arcane_unforging", "wh2_main_skill_all_magic_high_10_fiery_convocation"},
        },
        Dark = {
            InnateSkill = {"wh2_main_skill_magic_dark_lore_attribute",},
            SignatureSpell = {"wh2_main_skill_magic_dark_chillwind_dummy", },
            Level1DefaultSpells = {"wh2_main_skill_magic_dark_power_of_darkness", "wh2_main_skill_magic_dark_word_of_pain", "wh2_main_skill_magic_dark_bladewind", },
            Level1DefaultSpellsLord = {"wh2_main_skill_magic_dark_power_of_darkness_lord", "wh2_main_skill_magic_dark_word_of_pain_lord", "wh2_main_skill_magic_dark_bladewind_lord", },
            Level3DefaultSpells = {"wh2_main_skill_magic_dark_doombolt", "wh2_main_skill_magic_dark_soul_stealer", },
            Level3DefaultSpellsLord = {"wh2_main_skill_magic_dark_doombolt_lord", "wh2_main_skill_magic_dark_soul_stealer_lord", },
        },
        Deep = {
            InnateSkill = {"wh2_dlc11_skill_all_magic_deep_03_lore_attribute",},
            SignatureSpell = {"wh2_dlc11_skill_all_magic_deep_01_spiteful_shot",},
            Level1DefaultSpells = {"wh2_dlc11_skill_all_magic_deep_02_tidecall", "wh2_dlc11_skill_all_magic_deep_04_denizens_of_the_deep", "wh2_dlc11_skill_all_magic_deep_05_fog_of_the_damned", },
            Level1DefaultSpellsLord = {"wh2_dlc11_skill_all_magic_deep_02_tidecall_lord", "wh2_dlc11_skill_all_magic_deep_04_denizens_of_the_deep_lord", "wh2_dlc11_skill_all_magic_deep_05_fog_of_the_damned_lord", },
            Level3DefaultSpells = {"wh2_dlc11_skill_all_magic_deep_09_krakens_pull", "wh2_dlc11_skill_all_magic_deep_10_ghost_ship", },
            Level3DefaultSpellsLord = {"wh2_dlc11_skill_all_magic_deep_09_krakens_pull_lord", "wh2_dlc11_skill_all_magic_deep_10_ghost_ship_lord", },
        },
        Nehekhara = {
            InnateSkill = {"wh2_dlc09_skill_tmb_nehekhara_lore_1_passive",},
            SignatureSpell = {"wh2_dlc09_skill_tmb_nehekhara_lore_0_djafs_incantation_of_cursed_blades", "wh2_dlc09_skill_tmb_nehekhara_lore_0_djafs_incantation_of_cursed_blades_lord", },
            Level1DefaultSpells = {"wh2_dlc09_skill_tmb_nehekhara_lore_2_nerus_incantation_of_protection", "wh2_dlc09_skill_tmb_nehekhara_lore_3_ptras_incantation_of_righteous_smiting", "wh2_dlc09_skill_tmb_nehekhara_lore_4_usirians_incantation_of_vengeance"},
            Level1DefaultSpellsLord = {"wh2_dlc09_skill_tmb_nehekhara_lore_2_nerus_incantation_of_protection_lord", "wh2_dlc09_skill_tmb_nehekhara_lore_3_ptras_incantation_of_righteous_smiting_lord", "wh2_dlc09_skill_tmb_nehekhara_lore_4_usirians_incantation_of_vengeance_lord", },
            Level3DefaultSpells = {"wh2_dlc09_skill_tmb_nehekhara_lore_6_usekhps_incantation_of_desiccation", "wh2_dlc09_skill_tmb_nehekhara_lore_7_sakhmets_incantation_of_the_skullstorm"},
            Level3DefaultSpellsLord = {"wh2_dlc09_skill_tmb_nehekhara_lore_6_usekhps_incantation_of_desiccation_lord", "wh2_dlc09_skill_tmb_nehekhara_lore_7_sakhmets_incantation_of_the_skullstorm_lord",},
        },
        BigWaaagh = {
            InnateSkill = {"wh_main_skill_grn_magic_big_waaagh_04_power_of_da_waaagh",},
            SignatureSpell = {"wh_main_skill_grn_magic_big_waaagh_01_gaze_of_mork",},
            Level1DefaultSpells = {"wh_main_skill_grn_magic_big_waaagh_02_brain_bursta", "wh_main_skill_grn_magic_big_waaagh_03_fists_of_gork", "wh_main_skill_grn_magic_big_waaagh_05_eadbutt", },
            Level1DefaultSpellsLord = {"wh2_main_skill_grn_magic_big_waaagh_02_brain_bursta_lord", "wh2_main_skill_grn_magic_big_waaagh_03_fists_of_gork_lord", "wh2_main_skill_grn_magic_big_waaagh_05_eadbutt_lord", },
            Level3DefaultSpells = {"wh_main_skill_grn_magic_big_waaagh_10_foot_of_gork", "wh_main_skill_grn_magic_big_waaagh_09_ere_we_go"},
            Level3DefaultSpellsLord = {"wh2_main_skill_grn_magic_big_waaagh_09_ere_we_go_lord", "wh2_main_skill_grn_magic_big_waaagh_10_foot_of_gork_lord", },
        },
        LilWaaagh = {
            InnateSkill = {"wh_main_skill_grn_magic_little_waaagh_03_sneaky_stealin", },
            SignatureSpell = {"wh_main_spell_lil_waaagh_sneaky_stabbin", "wh_main_skill_grn_magic_little_waaagh_01_sneaky_stabbin",},
            Level1DefaultSpells = {"wh_main_skill_grn_magic_little_waaagh_02_vindictive_glare", "wh_main_skill_grn_magic_little_waaagh_04_itchy_nuisance", "wh_main_skill_grn_magic_little_waaagh_05_gorkll_fix_it", "wh2_main_skill_grn_magic_little_waaagh_04_itchy_nuisance_lord", "wh_main_spell_lil_waaagh_vindictive_glare", "wh2_main_skill_grn_magic_little_waaagh_02_vindictive_glare_lord", },
            Level1DefaultSpellsLord = {"wh2_main_skill_grn_magic_little_waaagh_02_vindictive_glare_lord", "wh2_main_skill_grn_magic_little_waaagh_04_itchy_nuisance_lord", "wh2_main_skill_grn_magic_little_waaagh_05_gorkll_fix_it_lord", },
            Level3DefaultSpells = {"wh_main_skill_grn_magic_little_waaagh_09_night_shroud", "wh2_main_skill_grn_magic_little_waaagh_09_night_shroud_lord", "wh_main_skill_grn_magic_little_waaagh_10_curse_of_da_bad_moon", "wh2_main_skill_grn_magic_little_waaagh_10_curse_of_da_bad_moon_lord",},
            Level3DefaultSpellsLord = {"wh2_main_skill_grn_magic_little_waaagh_09_night_shroud_lord", "wh2_main_skill_grn_magic_little_waaagh_10_curse_of_da_bad_moon_lord", },
        },
        Wild = {
            InnateSkill = {"wh_dlc03_skill_magic_wild_bestial_surge", },
            SignatureSpell = {"wh_dlc03_skill_magic_wild_viletide", },
            Level1DefaultSpells = {"wh_dlc03_skill_magic_wild_devolve", "wh_dlc03_skill_magic_wild_bray_scream", "wh_dlc03_skill_magic_wild_traitor_kin", },
            Level1DefaultSpellsLord = {"wh2_main_skill_magic_wild_devolve_lord", "wh2_main_skill_magic_wild_bray_scream_lord", "wh2_main_skill_magic_wild_traitor_kin_lord", },
            Level3DefaultSpells = {"wh_dlc03_skill_magic_wild_mantle_of_ghorok", "wh_dlc03_skill_magic_wild_savage_dominion", },
            Level3DefaultSpellsLord = {"wh2_main_skill_magic_wild_mantle_of_ghorok_lord", "wh2_main_skill_magic_wild_savage_dominion_lord", },
        },
        Plague = {
            InnateSkill = {"wh2_main_skill_all_magic_plague_03_lore_attribute",},
            SignatureSpell = {"wh2_main_skill_all_magic_plague_01_pestilent_breath",},
            Level1DefaultSpells = {"wh2_main_skill_all_magic_plague_02_bless_with_filth", "wh2_main_skill_all_magic_plague_04_wither", "wh2_main_skill_all_magic_plague_05_vermintide", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_plague_02_bless_with_filth_lord", "wh2_main_skill_all_magic_plague_04_wither_lord", "wh2_main_skill_all_magic_plague_05_vermintide_lord", },
            Level3DefaultSpells = {"wh2_main_skill_all_magic_plague_09_plague", "wh2_main_skill_all_magic_plague_11_pestilent_birth", },
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_plague_09_plague_lord", "wh2_main_skill_all_magic_plague_11_pestilent_birth_lord", },
        },
        GreySeerPlague = {
            InnateSkill = {"wh2_main_skill_all_magic_plague_03_lore_attribute",},
            SignatureSpell = {"wh2_main_skill_all_magic_plague_01_pestilent_breath",},
            Level1DefaultSpells = {"wh2_main_skill_all_magic_plague_02_bless_with_filth", "wh2_main_skill_all_magic_plague_04_wither", "wh2_main_skill_all_magic_plague_05_vermintide", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_plague_02_bless_with_filth_lord", "wh2_main_skill_all_magic_plague_04_wither_lord", "wh2_main_skill_all_magic_plague_05_vermintide_lord", },
            Level3DefaultSpells = {"wh2_main_skill_all_magic_plague_09_plague", "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth", "wh2_main_skill_all_magic_plague_11_pestilent_birth", },
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_plague_09_plague_lord", "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth", "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth", },
        },
        Ruin = {
            InnateSkill = {"wh2_main_skill_all_magic_ruin_03_lore_attribute", },
            SignatureSpell = {"wh2_main_skill_all_magic_ruin_01_warp_lightning", "wh2_main_skill_all_magic_ruin_01_warp_lightning_warlock", },
            Level1DefaultSpells = {"wh2_main_skill_all_magic_ruin_02_howling_warpgale_warlock", "wh2_main_skill_all_magic_ruin_04_death_frenzy_warlock", "wh2_main_skill_all_magic_ruin_05_skaven_scorch_warlock", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_ruin_02_howling_warpgale_lord", "wh2_main_skill_all_magic_ruin_04_death_frenzy_lord", "wh2_main_skill_all_magic_ruin_05_skaven_scorch_lord", },
            Level3DefaultSpells = {"wh2_main_skill_all_magic_ruin_09_cracks_call_warlock", "wh2_main_skill_all_magic_ruin_10_skitterleap_warlock", },
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_ruin_09_cracks_call_lord", "wh2_main_skill_all_magic_ruin_10_skitterleap_warlock", },
        },
        GreySeerRuin = {
            InnateSkill = {"wh2_main_skill_all_magic_ruin_03_lore_attribute", },
            SignatureSpell = {"wh2_main_skill_all_magic_ruin_01_warp_lightning", "wh2_main_skill_all_magic_ruin_01_warp_lightning_warlock", },
            Level1DefaultSpells = {"wh2_main_skill_all_magic_ruin_02_howling_warpgale_warlock", "wh2_main_skill_all_magic_ruin_04_death_frenzy_warlock", "wh2_main_skill_all_magic_ruin_05_skaven_scorch_warlock", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_ruin_02_howling_warpgale_lord", "wh2_main_skill_all_magic_ruin_04_death_frenzy_lord", "wh2_main_skill_all_magic_ruin_05_skaven_scorch_lord", },
            Level3DefaultSpells = {"wh2_main_skill_all_magic_ruin_09_cracks_call_warlock", "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth", },
            Level3DefaultSpellsLord = {"wh2_main_skill_all_magic_ruin_09_cracks_call_lord", "wh2_main_skill_all_magic_plague_10_dreaded_thirteenth", },
        },
        Slann = {
            InnateSkill = {},
            SignatureSpell = { },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {},
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {},
        },
        LoremasterOfHoeth = {
            InnateSkill = {},
            SignatureSpell = {"wh2_main_skill_magic_beasts_wyssans_wildform_loremaster", "wh2_main_skill_magic_death_01_spirit_leech_loremaster", "wh_main_skill_all_magic_fire_dummy_fireball", "wh2_main_skill_magic_heavens_01_harmonic_convergence_loremaster", "wh_dlc05_skill_magic_life_wizard_earth_blood", "wh_main_skill_all_magic_light_dummy_shems_burning_gaze", "wh_main_skill_all_magic_metal_dummy_searing_doom", "wh_dlc05_skill_magic_shadow_mystifying_miasma", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {},
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {},
        },
        Teclis = {
            InnateSkill = {},
            SignatureSpell = { },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {},
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {},
        },
        Mannfred = {
            InnateSkill = {},
            SignatureSpell = { },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {},
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {},
        },
        Azhag = {
            InnateSkill = {"wh_main_skill_all_magic_death_03_life_leeching",},
            SignatureSpell = {"wh_main_skill_all_magic_death_dummy_spirit_leech", },
            Level1DefaultSpells = {"wh_main_skill_all_magic_death_02_aspect_of_the_dreadknight", "wh_main_skill_all_magic_death_05_doom_and_darkness", "wh_main_skill_all_magic_death_04_soulblight", },
            Level1DefaultSpellsLord = {"wh2_main_skill_all_magic_death_02_aspect_of_the_dreadknight_lord", "wh2_main_skill_all_magic_death_05_doom_and_darkness_lord", "wh2_main_skill_all_magic_death_04_soulblight_lord",},
            Level3DefaultSpells = {"wh_main_skill_all_magic_death_09_the_fate_of_bjuna", "wh_main_skill_all_magic_death_10_the_purple_sun_of_xereus", },
            Level3DefaultSpellsLord = { "wh2_main_skill_all_magic_death_09_the_fate_of_bjuna_lord", "wh2_main_skill_all_magic_death_10_the_purple_sun_of_xereus_lord",},
        },
        BranchWraith = {
            InnateSkill = {"wh_dlc05_skill_magic_shadow_smoke_and_mirrors", },
            SignatureSpell = {"wh_dlc05_skill_magic_shadow_mystifying_miasma_branchwraith", },
            Level1DefaultSpells = {"wh_dlc05_skill_magic_life_wizard_awakening_of_the_wood_branchwraith", "wh_dlc05_skill_magic_shadow_the_withering_branchwraith", "wh_dlc05_skill_magic_shadow_penumbral_pendulum_branchwraith", },
            Level1DefaultSpellsLord = {},
            Level3DefaultSpells = {"wh_dlc05_skill_magic_life_wizard_earth_blood_branchwraith", "wh_dlc05_skill_magic_life_wizard_shield_of_thorns_branchwraith", },
            Level3DefaultSpellsLord = {},
        },
        GhorstLoreVampires = {
            InnateSkill = {"wh_main_skill_vmp_magic_vampires_helman_03_the_curse_of_undeath", },
            SignatureSpell = {"wh2_main_skill_vmp_magic_vampires_02_vanhels_danse_macabre_lord", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh_main_skill_vmp_magic_vampires_01_invocation_of_nehek", "wh2_main_skill_vmp_magic_vampires_04_gaze_of_nagash_lord", "wh_main_skill_vmp_magic_vampires_05_helman_raise_dead", },
            Level3DefaultSpells = { },
            Level3DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_09_curse_of_years_lord", "wh2_main_skill_vmp_magic_vampires_10_wind_of_death_lord", },
        },
        VampiresGhoulKing = {
            InnateSkill = {"wh_main_skill_vmp_magic_vampires_03_the_curse_of_undeath",},
            SignatureSpell = {"wh_dlc04_skill_vmp_magic_strigoi_01_invocation_of_nehek", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh_dlc04_skill_all_magic_strigoi_01_spirit_leech", "wh_dlc04_skill_vmp_magic_strigoi_04_gaze_of_nagash", "wh_dlc04_skill_vmp_magic_strigoi_05_raise_dead", },
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {"wh_dlc04_skill_vmp_magic_strigoi_04_soulblight", "wh_dlc04_skill_vmp_magic_strigoi_05_doom_and_darkness", },
        },
        VampiresVonCarstein = {
            InnateSkill = {"wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_curse_of_undeath",},
            SignatureSpell = {"wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_invocation_of_nehek", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_vanhels_danse_macabre", "wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_flock_of_doom", "wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_raise_dead", },
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {"wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_transformation_of_kadon", "wh2_dlc11_skill_vmp_bloodline_von_carstein_magic_wind_of_death", },
        },
        VampiresLahmian = {
            InnateSkill = {"wh2_dlc11_skill_vmp_bloodline_lahmian_magic_curse_of_undeath",},
            SignatureSpell = {"wh_main_skill_vmp_magic_vampires_01_invocation_of_nehek", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh2_dlc11_skill_vmp_bloodline_lahmian_magic_the_enfeebling_foe", "wh2_dlc11_skill_vmp_bloodline_lahmian_magic_penumbral_pendulum", "wh2_dlc11_skill_vmp_bloodline_lahmian_magic_raise_dead", },
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {"wh2_dlc11_skill_vmp_bloodline_lahmian_magic_okkams_mindrazor", "wh2_dlc11_skill_vmp_bloodline_lahmian_magic_wind_of_death", },
        },
        VampiresNecrarch = {
            InnateSkill = {"wh2_dlc11_skill_vmp_bloodline_necrarch_magic_curse_of_undeath",},
            SignatureSpell = {"wh2_dlc11_skill_vmp_bloodline_necrarch_magic_invocation_of_nehek", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh2_dlc11_skill_vmp_bloodline_necrarch_magic_spirit_leech", "wh2_dlc11_skill_vmp_bloodline_necrarch_magic_panns_pelt", "wh2_dlc11_skill_vmp_bloodline_necrarch_magic_raise_dead", },
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {"wh2_dlc11_skill_vmp_bloodline_necrarch_magic_curse_of_anraheir", "wh2_dlc11_skill_vmp_bloodline_necrarch_magic_purple_sun", },
        },
        VampiresStrigoiBloodline = {
            InnateSkill = {"wh_main_skill_vmp_magic_vampires_03_the_curse_of_undeath",},
            SignatureSpell = {"wh_dlc04_skill_vmp_magic_strigoi_01_invocation_of_nehek", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh_dlc04_skill_all_magic_strigoi_01_spirit_leech", "wh_dlc04_skill_vmp_magic_strigoi_04_gaze_of_nagash", "wh_dlc04_skill_vmp_magic_strigoi_05_raise_dead", },
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {"wh_dlc04_skill_vmp_magic_strigoi_04_soulblight", "wh_dlc04_skill_vmp_magic_strigoi_05_doom_and_darkness", },
        },
        VampiresBloodDragon = {
            InnateSkill = {"wh_main_skill_vmp_magic_vampires_03_the_curse_of_undeath",},
            SignatureSpell = {"wh_main_skill_vmp_magic_vampires_01_invocation_of_nehek", },
            Level1DefaultSpells = {},
            Level1DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_02_vanhels_danse_macabre_lord", "wh2_main_skill_vmp_magic_vampires_04_gaze_of_nagash_lord", "wh2_main_skill_vmp_magic_vampires_05_raise_dead_lord", },
            Level3DefaultSpells = {},
            Level3DefaultSpellsLord = {"wh2_main_skill_vmp_magic_vampires_09_curse_of_years_lord", "wh2_main_skill_vmp_magic_vampires_10_wind_of_death_lord", },
        },
        Stealth = {
            InnateSkill = {"wh2_dlc14_skill_all_magic_stealth_02_toxic_rain_lore_attribute",},
            SignatureSpell = {"wh2_dlc14_skill_all_magic_stealth_01_warp_stars", },
            Level1DefaultSpells = {"wh2_dlc14_skill_all_magic_stealth_03_skitterleap", "wh2_dlc14_skill_all_magic_stealth_04_armour_of_darkness", "wh2_dlc14_skill_all_magic_stealth_05_veil_of_shadows", },
            Level1DefaultSpellsLord = {},
            Level3DefaultSpells = {"wh2_dlc14_skill_all_magic_stealth_06_brittle_bone", "wh2_dlc14_skill_all_magic_stealth_07_black_whirlwind", },
            Level3DefaultSpellsLord = {},
        },
        -- Non Vanilla
        Ice = {
            InnateSkill = {"mixu_all_lord_spell_lore_of_ice_passive",},
            SignatureSpell = {"mixu_all_lord_spell_lore_of_ice_glacial_barrier", },
            Level1DefaultSpells = { "mixu_all_lord_spell_lore_of_ice_shield_of_cold", "mixu_all_lord_spell_lore_of_ice_midwinters_kiss", "mixu_all_lord_spell_lore_of_ice_wind_of_ice", },
            Level1DefaultSpellsLord = { "mixu_all_lord_spell_lore_of_ice_shield_of_cold", "mixu_all_lord_spell_lore_of_ice_midwinters_kiss", "mixu_all_lord_spell_lore_of_ice_wind_of_ice", },
            Level3DefaultSpells = { "mixu_all_lord_spell_lore_of_ice_shardstorm", "mixu_all_lord_spell_lore_of_ice_invocation_of_the_ice_storm", },
            Level3DefaultSpellsLord = { "mixu_all_lord_spell_lore_of_ice_shardstorm", "mixu_all_lord_spell_lore_of_ice_invocation_of_the_ice_storm", },
        },
    };
end